version: "3.3"
services:
  traefik:
    image: traefik:2.4
    container_name: traefik
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-data/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-data/acme.json:/acme.json
      - /etc/letsencrypt/:/letsencrypt/
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY=a8d4fe16e8f34470"
      - "OVH_APPLICATION_SECRET=c61b39674320b18a65e78a31588839dc"
      - "OVH_CONSUMER_KEY=73344e34ce307388240c583a74320670"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.api.rule=Host(`traefik.kimchi.ovh`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.tls.domains[0].main=traefik.kimchi.ovh"
      - "traefik.http.routers.httpapi.entrypoints=web"
      - "traefik.http.routers.httpapi.rule=Host(`traefik.kimchi.ovh`)"
      - "traefik.http.services.api.loadbalancer.server.port=8081"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.api-auth.basicauth.users=jonathan:$$apr1$$1kjZC3Od$$en86Nk47Jmyi/Yudkedms1"
      - 'traefik.http.routers.api.middlewares=api-auth'
networks:
  traefik-public:
    external: true
